-- USE Bamazon 
-- CREATE TABLE Products(
--   id INTEGER(11) AUTO_INCREMENT NOT NULL,
--   ProductName VARCHAR(100) NULL,
--   DepartmentName VARCHAR(100) NULL,
--   Price VARCHAR(100) NULL,
--   StockQuantity VARCHAR(1000)NOT NULLProducts,
--   PRIMARY KEY (`id`)
-- );
select * from Products;
-- INSERT INTO Products (ProductName, DepartmentName, Price, StockQuantity)
-- VALUES ("Brown rice", "Pasta and Rice", 4, 550);
-- 